// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: proto/contract.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "contract";

export interface CreateContractDto {
  roomId: string;
  content: string;
  startDate: string;
  endDate: string;
  deposit: number;
  rentAmount: number;
  templateId: string;
}

export interface PaginationDto {
  page: number;
  limit: number;
}

export interface FindOneContractDto {
  contracId: string;
}

export interface UpdateContractDto {
  contractId: string;
  isActive: boolean;
  roomId: string;
  content: string;
  startDate: string;
  endDate: string;
  deposit: number;
  rentAmount: number;
  templateId: string;
}

export interface Contract {
  contractId: string;
  isActive: boolean;
  roomId: string;
  content: string;
  createdAt: string;
  updatedAt: string;
  startDate: string;
  endDate: string;
  deposit: number;
  rentAmount: number;
  templateId: string;
}

export interface Contracts {
  contracts: Contract[];
  total: number;
}

export interface CreateContractTemplateDto {
  name: string;
  description: string;
  content: string;
}

export interface FindOneContractTemplateDto {
  templateId: string;
}

export interface UpdateContractTemplateDto {
  templateId: string;
  name: string;
  description: string;
  content: string;
}

export interface ContractTemplate {
  templateId: string;
  name: string;
  description: string;
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface ContractTemplates {
  contractTemplates: ContractTemplate[];
  total: number;
}

export const CONTRACT_PACKAGE_NAME = "contract";

export interface ContractServiceClient {
  createContract(request: CreateContractDto): Observable<Contract>;

  findAllContracts(request: PaginationDto): Observable<Contracts>;

  findOneContract(request: FindOneContractDto): Observable<Contract>;

  updateContract(request: UpdateContractDto): Observable<Contract>;

  removeContract(request: FindOneContractDto): Observable<Contract>;

  createContractTemplate(request: CreateContractTemplateDto): Observable<ContractTemplate>;

  findAllContractTemplates(request: PaginationDto): Observable<ContractTemplates>;

  findOneContractTemplate(request: FindOneContractTemplateDto): Observable<ContractTemplate>;

  updateContractTemplate(request: UpdateContractTemplateDto): Observable<ContractTemplate>;

  removeContractTemplate(request: FindOneContractTemplateDto): Observable<ContractTemplate>;
}

export interface ContractServiceController {
  createContract(request: CreateContractDto): Promise<Contract> | Observable<Contract> | Contract;

  findAllContracts(request: PaginationDto): Promise<Contracts> | Observable<Contracts> | Contracts;

  findOneContract(request: FindOneContractDto): Promise<Contract> | Observable<Contract> | Contract;

  updateContract(request: UpdateContractDto): Promise<Contract> | Observable<Contract> | Contract;

  removeContract(request: FindOneContractDto): Promise<Contract> | Observable<Contract> | Contract;

  createContractTemplate(
    request: CreateContractTemplateDto,
  ): Promise<ContractTemplate> | Observable<ContractTemplate> | ContractTemplate;

  findAllContractTemplates(
    request: PaginationDto,
  ): Promise<ContractTemplates> | Observable<ContractTemplates> | ContractTemplates;

  findOneContractTemplate(
    request: FindOneContractTemplateDto,
  ): Promise<ContractTemplate> | Observable<ContractTemplate> | ContractTemplate;

  updateContractTemplate(
    request: UpdateContractTemplateDto,
  ): Promise<ContractTemplate> | Observable<ContractTemplate> | ContractTemplate;

  removeContractTemplate(
    request: FindOneContractTemplateDto,
  ): Promise<ContractTemplate> | Observable<ContractTemplate> | ContractTemplate;
}

export function ContractServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createContract",
      "findAllContracts",
      "findOneContract",
      "updateContract",
      "removeContract",
      "createContractTemplate",
      "findAllContractTemplates",
      "findOneContractTemplate",
      "updateContractTemplate",
      "removeContractTemplate",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ContractService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ContractService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTRACT_SERVICE_NAME = "ContractService";
