// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: proto/rental.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "rental";

/** Room Messages */
export interface CreateRoomDto {
  roomNumber: string;
  price: number;
  address: string;
  isEmpty: boolean;
}

export interface UpdateRoomDto {
  id: string;
  roomNumber: string;
  price: number;
  address: string;
  isEmpty: boolean;
}

export interface FindAllRoomsDto {
  page: number;
  limit: number;
}

export interface FindOneRoomDto {
  id: string;
}

export interface Room {
  id: string;
  roomNumber: string;
  price: number;
  address: string;
  isEmpty: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Rooms {
  rooms: Room[];
  total: number;
}

/** Tenant Messages */
export interface CreateTenantDto {
  name: string;
  email: string;
  phone: string;
  roomId: string;
  isLeadRoom: boolean;
  identityNumber: string;
  permanentAddress: string;
  startDate: string;
}

export interface UpdateTenantDto {
  id: string;
  name: string;
  email: string;
  phone: string;
  roomId: string;
  isLeadRoom: boolean;
  identityNumber: string;
  permanentAddress: string;
  startDate: string;
  isActive: boolean;
}

export interface FindOneTenantDto {
  id: string;
}

export interface FindAllTenantsByFilterDto {
  roomId?: string | undefined;
  isLeadRoom?: boolean | undefined;
  page: number;
  limit: number;
}

export interface Tenant {
  id: string;
  name: string;
  email: string;
  phone: string;
  roomId: string;
  isLeadRoom: boolean;
  identityNumber: string;
  permanentAddress: string;
  startDate: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Tenants {
  tenants: Tenant[];
  total: number;
}

/** Fee Message */
export interface Fee {
  type: string;
  amount: number;
  reading: number;
  description: string;
  createdAt: string;
  updatedAt: string;
}

/** Invoice Messages */
export interface CreateInvoiceDto {
  roomId: string;
  month: string;
  fees: Fee[];
  total: number;
  dueDate: string;
}

export interface UpdateInvoiceDto {
  id: string;
  roomId: string;
  month: string;
  fees: Fee[];
  total: number;
  dueDate: string;
  isPaid: boolean;
}

export interface FindOneInvoiceDto {
  id: string;
}

export interface FindAllInvoicesByFilterDto {
  page: number;
  limit: number;
  isPaid?: boolean | undefined;
  roomId?: string | undefined;
  month?: string | undefined;
}

export interface Invoice {
  id: string;
  roomId: string;
  month: string;
  fees: Fee[];
  total: number;
  dueDate: string;
  isPaid: boolean;
  paidAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Invoices {
  invoices: Invoice[];
  total: number;
}

/** Readings Messages */
export interface FindLatestReadingsDto {
  roomId: string;
}

export interface ReadingsResponse {
  readings: { [key: string]: number };
}

export interface ReadingsResponse_ReadingsEntry {
  key: string;
  value: number;
}

export const RENTAL_PACKAGE_NAME = "rental";

export interface OrderServiceClient {
  /** Room */

  createRoom(request: CreateRoomDto): Observable<Room>;

  findAllRooms(request: FindAllRoomsDto): Observable<Rooms>;

  findOneRoom(request: FindOneRoomDto): Observable<Room>;

  updateRoom(request: UpdateRoomDto): Observable<Room>;

  removeRoom(request: FindOneRoomDto): Observable<Room>;

  /** Tenant */

  createTenant(request: CreateTenantDto): Observable<Tenant>;

  findAllTenantsByFilter(request: FindAllTenantsByFilterDto): Observable<Tenants>;

  findOneTenant(request: FindOneTenantDto): Observable<Tenant>;

  updateTenant(request: UpdateTenantDto): Observable<Tenant>;

  removeTenant(request: FindOneTenantDto): Observable<Tenant>;

  /** Invoice */

  createInvoice(request: CreateInvoiceDto): Observable<Invoice>;

  findAllInvoicesByFilter(request: FindAllInvoicesByFilterDto): Observable<Invoices>;

  findOneInvoice(request: FindOneInvoiceDto): Observable<Invoice>;

  updateInvoice(request: UpdateInvoiceDto): Observable<Invoice>;

  removeInvoice(request: FindOneInvoiceDto): Observable<Invoice>;

  /** Readings */

  findLatestReadings(request: FindLatestReadingsDto): Observable<ReadingsResponse>;
}

export interface OrderServiceController {
  /** Room */

  createRoom(request: CreateRoomDto): Promise<Room> | Observable<Room> | Room;

  findAllRooms(request: FindAllRoomsDto): Promise<Rooms> | Observable<Rooms> | Rooms;

  findOneRoom(request: FindOneRoomDto): Promise<Room> | Observable<Room> | Room;

  updateRoom(request: UpdateRoomDto): Promise<Room> | Observable<Room> | Room;

  removeRoom(request: FindOneRoomDto): Promise<Room> | Observable<Room> | Room;

  /** Tenant */

  createTenant(request: CreateTenantDto): Promise<Tenant> | Observable<Tenant> | Tenant;

  findAllTenantsByFilter(request: FindAllTenantsByFilterDto): Promise<Tenants> | Observable<Tenants> | Tenants;

  findOneTenant(request: FindOneTenantDto): Promise<Tenant> | Observable<Tenant> | Tenant;

  updateTenant(request: UpdateTenantDto): Promise<Tenant> | Observable<Tenant> | Tenant;

  removeTenant(request: FindOneTenantDto): Promise<Tenant> | Observable<Tenant> | Tenant;

  /** Invoice */

  createInvoice(request: CreateInvoiceDto): Promise<Invoice> | Observable<Invoice> | Invoice;

  findAllInvoicesByFilter(request: FindAllInvoicesByFilterDto): Promise<Invoices> | Observable<Invoices> | Invoices;

  findOneInvoice(request: FindOneInvoiceDto): Promise<Invoice> | Observable<Invoice> | Invoice;

  updateInvoice(request: UpdateInvoiceDto): Promise<Invoice> | Observable<Invoice> | Invoice;

  removeInvoice(request: FindOneInvoiceDto): Promise<Invoice> | Observable<Invoice> | Invoice;

  /** Readings */

  findLatestReadings(
    request: FindLatestReadingsDto,
  ): Promise<ReadingsResponse> | Observable<ReadingsResponse> | ReadingsResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createRoom",
      "findAllRooms",
      "findOneRoom",
      "updateRoom",
      "removeRoom",
      "createTenant",
      "findAllTenantsByFilter",
      "findOneTenant",
      "updateTenant",
      "removeTenant",
      "createInvoice",
      "findAllInvoicesByFilter",
      "findOneInvoice",
      "updateInvoice",
      "removeInvoice",
      "findLatestReadings",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
